name: Angular CLI

on:
    push:
        branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '24.15.0'

    - name: Install Dependencies         
      uses: npm install
      
    - name: Build Angular App       
      run: npm run build
